# Generated by Django 5.2.4 on 2025-07-20 20:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_tag_note_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('start_date', models.DateField(blank=True, help_text='Start date (was previously due_date).', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date (must be on or after start date).', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1)),
                ('repeat', models.CharField(blank=True, help_text='e.g. daily, weekly, custom, etc.', max_length=20, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_days', models.CharField(blank=True, help_text='Comma-separated day codes if using a custom pattern (e.g. MON,WED,FRI).', max_length=50, null=True)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('repeat_forever', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='blue', help_text='Colour used in calendar or list view.', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical task',
                'verbose_name_plural': 'historical tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, help_text='Start date (was previously due_date).', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date (must be on or after start date).', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1)),
                ('repeat', models.CharField(blank=True, help_text='e.g. daily, weekly, custom, etc.', max_length=20, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_days', models.CharField(blank=True, help_text='Comma-separated day codes if using a custom pattern (e.g. MON,WED,FRI).', max_length=50, null=True)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('repeat_forever', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='blue', help_text='Colour used in calendar or list view.', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='Task.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
