# Generated by Django 5.2.4 on 2025-07-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_historicaltask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
